### ISSUE TITLE
Obtain access to the NPM repository

### ISSUE THREAD

**Issue by stephenyeargin** [raventools/hubot-zendesk#2]
@wjbeckett : Do you mind if I get access to push to https://www.npmjs.com/package/hubot-zendesk ? It looks like you've deleted the original repository, and we'd like to pin against NPM if possible. My username on NPM is `stephenyeargin`.

Thanks!

**Comment by wjbeckett** [comment]
@stephenyeargin: I've given you access to the npm repo. Sorry for that. I don't use hubot anymore so didn't need it any longer.

**Comment by stephenyeargin** [comment]
@wjbeckett Thanks man!

**Comment by wjbeckett** [comment]
No problem at all.
Let me know if you have any issues!
